//This file was generated by script mkregs.py

//address width
`define iob_ssd_swreg_ADDR_W 2

//address macros
//Write addresses
`define SSD_DATA_IN_ADDR 0
`define SSD_RATE_ADDR 4
//Read Addresses

//register/mem data width
`define SSD_DATA_IN_W 16
`define SSD_RATE_W 32

//mem address width
